import { defineTool } from "eve/tools";
import { always } from "eve/tools/approval";
import { z } from "zod";
import { loadVercelDeployConfig, collectSandboxFiles, createVercelDeployment, pollDeploymentReady } from "../lib/vercel-deploy";
import { getOrCreateServiceRevenueSecret } from "../lib/service-secret";
import { registerService, activeServiceCount, findServiceByName } from "../lib/services";

/** Bounds how much Vercel infra a single automaton can spin up unattended. */
const MAX_ACTIVE_SERVICES = 5;

/**
 * Node helper a deployed service can require() to charge real customers via
 * Stripe Checkout and have proceeds land straight in the same ledger every
 * other Stripe flow in this app uses. This is the only payment path — an
 * earlier on-chain (x402/mppx-on-Tempo) path was tried and removed: it
 * needed real crypto funding with meaningfully more friction than expected
 * (bridging, credits not applying to arbitrary endpoints) for no benefit
 * over a plain card payment.
 */
function buildStripeHelper(checkoutUrl: string, confirmUrl: string, secret: string, serviceId: string, serviceName: string): string {
  return `// Auto-generated by deploy_service — do not hand-edit; the automaton owns this file.
// Usage from any Node HTTP handler:
//   const revenue = require('./_automaton_stripe');
//   const { checkoutUrl } = await revenue.charge(499, successUrl, cancelUrl);
//   // redirect the customer to checkoutUrl; once they return to your successUrl:
//   const result = await revenue.confirm(sessionId);
//   if (result.credited) { /* fulfill the paid request */ }

const CHECKOUT_URL = ${JSON.stringify(checkoutUrl)};
const CONFIRM_URL = ${JSON.stringify(confirmUrl)};
const SECRET = ${JSON.stringify(secret)};
const SERVICE_ID = ${JSON.stringify(serviceId)};
const SERVICE_NAME = ${JSON.stringify(serviceName)};

async function charge(amountCents, successUrl, cancelUrl) {
  const resp = await fetch(CHECKOUT_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-automaton-service-secret': SECRET },
    body: JSON.stringify({ amountCents, serviceName: SERVICE_NAME, successUrl, cancelUrl }),
  });
  return resp.json();
}

async function confirm(sessionId) {
  const resp = await fetch(CONFIRM_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-automaton-service-secret': SECRET },
    body: JSON.stringify({ sessionId, serviceId: SERVICE_ID, serviceName: SERVICE_NAME }),
  });
  return resp.json();
}

module.exports = { charge, confirm };
`;
}

export default defineTool({
  description:
    "Deploy a directory you've built in your sandbox (with bash/write_file) as its own real, public Vercel project — a genuine public URL others can reach and pay for, not a sandbox-only preview. This is how you actually host a paid service instead of just building one nobody can access. A ready-made `_automaton_stripe.js` helper is injected automatically for Node services: charges customers via real Stripe Checkout, proceeds land in your normal ledger. Every deployed service is registered and trackable via `list_services`/`check_service_status`, and revenue is attributed per-service. Capped at a handful of active services at once to bound infrastructure cost. Requires AUTOMATON_VERCEL_TOKEN to be configured. Always requires creator approval since it creates new billed infrastructure under your Vercel account.",
  approval: always(),
  inputSchema: z.object({
    name: z.string().min(1).max(64).describe("Project name — becomes part of the deployment URL"),
    sourceDir: z.string().min(1).describe("Absolute sandbox path to the directory to deploy, e.g. /workspace/services/my-api"),
    resumeDeploymentId: z
      .string()
      .optional()
      .describe("If a previous call returned TIMEOUT, pass its deploymentId here to re-poll instead of redeploying from scratch."),
  }),
  async execute({ name, sourceDir, resumeDeploymentId }, ctx) {
    const config = loadVercelDeployConfig();
    if (!config) {
      return {
        deployed: false,
        reason: "AUTOMATON_VERCEL_TOKEN is not set. The creator needs to add a Vercel API token (with deploy scope) as an env var before you can deploy public services.",
      };
    }

    if (resumeDeploymentId) {
      const resumed = await pollDeploymentReady(config, resumeDeploymentId);
      return {
        deployed: resumed.readyState === "READY",
        readyState: resumed.readyState,
        url: resumed.url,
        deploymentId: resumeDeploymentId,
        note: resumed.readyState === "TIMEOUT" ? "Still not ready — call again with the same resumeDeploymentId." : undefined,
      };
    }

    // A redeploy of an already-registered name reuses its slot and its
    // stable id — only a genuinely new name counts against the cap.
    const existingService = await findServiceByName(name);
    if (!existingService) {
      const activeCount = await activeServiceCount();
      if (activeCount >= MAX_ACTIVE_SERVICES) {
        return {
          deployed: false,
          reason: `Already at the cap of ${MAX_ACTIVE_SERVICES} active services. Use list_services to review them and remove_service one before deploying another (unless you're redeploying an existing name, which doesn't count against the cap) — this bounds how much billed infrastructure you can create unattended.`,
        };
      }
    }

    const sandbox = await ctx.getSandbox();
    const { files, truncated } = await collectSandboxFiles(sandbox, sourceDir);
    if (files.length === 0) {
      return { deployed: false, reason: `No readable files found under ${sourceDir}.` };
    }

    const appBaseUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL
      ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
      : process.env.APP_BASE_URL;
    const serviceId = existingService?.id ?? crypto.randomUUID();

    let stripeHelperIncluded = false;
    if (appBaseUrl) {
      const serviceSecret = await getOrCreateServiceRevenueSecret();
      files.push({
        file: "_automaton_stripe.js",
        data: buildStripeHelper(
          `${appBaseUrl}/api/service-revenue/checkout`,
          `${appBaseUrl}/api/service-revenue/confirm`,
          serviceSecret,
          serviceId,
          name,
        ),
      });
      stripeHelperIncluded = true;
    }

    const created = await createVercelDeployment(config, name, files);
    const finalState = await pollDeploymentReady(config, created.id);
    const readyUrl = finalState.url || created.url;

    let registeredId: string | undefined;
    if (finalState.readyState === "READY") {
      // May resolve to an existing entry if `name` was already deployed —
      // registerService upserts by name, so this redeploy doesn't eat
      // another slot against MAX_ACTIVE_SERVICES.
      const registered = await registerService({
        id: serviceId,
        name,
        url: readyUrl,
        deploymentId: created.id,
        sourceDir,
      });
      registeredId = registered.id;
    }

    return {
      deployed: finalState.readyState === "READY",
      readyState: finalState.readyState,
      url: readyUrl,
      deploymentId: created.id,
      serviceId: registeredId,
      filesDeployed: files.length,
      truncated,
      stripeHelperIncluded,
      note: finalState.readyState === "TIMEOUT"
        ? `Deployment is still building — call deploy_service again with resumeDeploymentId: "${created.id}" to check on it (it will not be registered as a service until ready).`
        : truncated
          ? "Some files were skipped (count/size caps) — keep services lean: source + package.json, no node_modules or build output."
          : undefined,
    };
  },
});
