import { defineTool } from "eve/tools";
import { always } from "eve/tools/approval";
import { z } from "zod";
import { loadVercelDeployConfig, collectSandboxFiles, createVercelDeployment, pollDeploymentReady } from "../lib/vercel-deploy";
import { getOrCreateWallet } from "../lib/wallet";
import { getOrCreateMppSecretKey } from "../lib/mpp-secret";
import { getOrCreateServiceRevenueSecret } from "../lib/service-secret";
import { registerService, activeServiceCount } from "../lib/services";

/** Bounds how much Vercel infra a single automaton can spin up unattended. */
const MAX_ACTIVE_SERVICES = 5;

/**
 * Node helper a deployed service can require() to charge real customers via
 * Stripe Checkout and have proceeds land straight in the same ledger every
 * other Stripe flow in this app uses — no wallet, no gas, no crypto at all.
 * This is the primary, recommended way to earn from a deployed service.
 */
function buildStripeHelper(checkoutUrl: string, confirmUrl: string, secret: string, serviceId: string, serviceName: string): string {
  return `// Auto-generated by deploy_service — do not hand-edit; the automaton owns this file.
// Usage from any Node HTTP handler:
//   const revenue = require('./_automaton_stripe');
//   const { checkoutUrl } = await revenue.charge(499, successUrl, cancelUrl);
//   // redirect the customer to checkoutUrl; once they return to your successUrl:
//   const result = await revenue.confirm(sessionId);
//   if (result.credited) { /* fulfill the paid request */ }

const CHECKOUT_URL = ${JSON.stringify(checkoutUrl)};
const CONFIRM_URL = ${JSON.stringify(confirmUrl)};
const SECRET = ${JSON.stringify(secret)};
const SERVICE_ID = ${JSON.stringify(serviceId)};
const SERVICE_NAME = ${JSON.stringify(serviceName)};

async function charge(amountCents, successUrl, cancelUrl) {
  const resp = await fetch(CHECKOUT_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-automaton-service-secret': SECRET },
    body: JSON.stringify({ amountCents, serviceName: SERVICE_NAME, successUrl, cancelUrl }),
  });
  return resp.json();
}

async function confirm(sessionId) {
  const resp = await fetch(CONFIRM_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-automaton-service-secret': SECRET },
    body: JSON.stringify({ sessionId, serviceId: SERVICE_ID, serviceName: SERVICE_NAME }),
  });
  return resp.json();
}

module.exports = { charge, confirm };
`;
}

/** Testnet pathUSD vs mainnet USDC on the Tempo network (per Stripe's & mppx's own docs). */
const TEMPO_CURRENCY = {
  testnet: "0x20c0000000000000000000000000000000000000",
  mainnet: "0x20c000000000000000000000b9537d11c60e8b50",
} as const;

/**
 * Node helper a deployed service can require() to accept real machine
 * payments via mppx (mpp.dev) — the real, spec-compliant library, not a
 * hand-rolled protocol implementation. Settles peer-to-peer on the Tempo
 * network straight to this automaton's own wallet address (a public
 * address, not the private key — mppx never needs the key). No gas held by
 * the automaton is required to receive a charge.
 */
function buildMppHelper(secretKey: string, recipientAddress: string, network: "testnet" | "mainnet", reportUrl?: string, reportSecret?: string): string {
  return `// Auto-generated by deploy_service — do not hand-edit; the automaton owns this file.
// Usage from any Node HTTP handler (Web-standard Request/Response):
//   const mpp = require('./_automaton_mpp');
//   export async function GET(request) {
//     const result = await mpp.charge(request, '0.01', 'Data retrieval');
//     if (!result.paid) return result.challenge;
//     return result.withReceipt(Response.json({ data: '...' }));
//   }

const { Mppx, tempo } = require('mppx/server');

const mppx = Mppx.create({
  methods: [tempo({ currency: ${JSON.stringify(TEMPO_CURRENCY[network])}, recipient: ${JSON.stringify(recipientAddress)} })],
  secretKey: ${JSON.stringify(secretKey)},
});

const REPORT_URL = ${JSON.stringify(reportUrl ?? null)};
const REPORT_SECRET = ${JSON.stringify(reportSecret ?? null)};

async function charge(request, amount, description) {
  const response = await mppx.charge({ amount: String(amount) })(request);
  if (response.status === 402) {
    return { paid: false, challenge: response.challenge };
  }
  // Fire-and-forget: purely so the creator's dashboard sees this. The
  // payment itself already settled on-chain by this point either way.
  if (REPORT_URL && REPORT_SECRET) {
    fetch(REPORT_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-automaton-mpp-secret': REPORT_SECRET },
      body: JSON.stringify({ amount, description: description || 'mppx (Tempo) payment' }),
    }).catch(() => {});
  }
  return { paid: true, withReceipt: response.withReceipt };
}

module.exports = { charge, mppx };
`;
}

/** Ensures package.json in the uploaded files declares mppx — Vercel installs it at build time, so the deployed service needs no manual npm install step. */
function ensureMppDependency(files: { file: string; data: string }[]): void {
  const pkgFile = files.find((f) => f.file === "package.json");
  if (!pkgFile) {
    files.push({
      file: "package.json",
      data: JSON.stringify({ name: "automaton-service", version: "1.0.0", private: true, dependencies: { mppx: "^0.8.12" } }, null, 2),
    });
    return;
  }
  try {
    const pkg = JSON.parse(pkgFile.data);
    pkg.dependencies = pkg.dependencies || {};
    if (!pkg.dependencies.mppx) pkg.dependencies.mppx = "^0.8.12";
    pkgFile.data = JSON.stringify(pkg, null, 2);
  } catch {
    // Malformed package.json is the agent's own problem to fix — don't silently overwrite it.
  }
}

export default defineTool({
  description:
    "Deploy a directory you've built in your sandbox (with bash/write_file) as its own real, public Vercel project — a genuine public URL others can reach and pay for, not a sandbox-only preview. This is how you actually host a paid service instead of just building one nobody can access. Two ready-made helpers are injected automatically for a Node service: `_automaton_stripe.js` (recommended — charges customers via Stripe Checkout, proceeds land in your normal ledger, no crypto or gas required) and `_automaton_mpp.js` (real machine-to-machine payments via mppx/mpp.dev, settled on the Tempo network straight to your own wallet address — no gas held by you required, since mppx handles fee-paying). Every deployed service is registered and trackable via `list_services`/`check_service_status`, and revenue is attributed per-service. Capped at a handful of active services at once to bound infrastructure cost. Requires AUTOMATON_VERCEL_TOKEN to be configured. Always requires creator approval since it creates new billed infrastructure under your Vercel account.",
  approval: always(),
  inputSchema: z.object({
    name: z.string().min(1).max(64).describe("Project name — becomes part of the deployment URL"),
    sourceDir: z.string().min(1).describe("Absolute sandbox path to the directory to deploy, e.g. /workspace/services/my-api"),
    mppNetwork: z
      .enum(["testnet", "mainnet"])
      .default("testnet")
      .describe("Tempo network for the mppx payment helper. Keep testnet until you've actually verified the flow end to end — mainnet charges real money."),
    resumeDeploymentId: z
      .string()
      .optional()
      .describe("If a previous call returned TIMEOUT, pass its deploymentId here to re-poll instead of redeploying from scratch."),
  }),
  async execute({ name, sourceDir, mppNetwork, resumeDeploymentId }, ctx) {
    const config = loadVercelDeployConfig();
    if (!config) {
      return {
        deployed: false,
        reason: "AUTOMATON_VERCEL_TOKEN is not set. The creator needs to add a Vercel API token (with deploy scope) as an env var before you can deploy public services.",
      };
    }

    if (resumeDeploymentId) {
      const resumed = await pollDeploymentReady(config, resumeDeploymentId);
      return {
        deployed: resumed.readyState === "READY",
        readyState: resumed.readyState,
        url: resumed.url,
        deploymentId: resumeDeploymentId,
        note: resumed.readyState === "TIMEOUT" ? "Still not ready — call again with the same resumeDeploymentId." : undefined,
      };
    }

    const activeCount = await activeServiceCount();
    if (activeCount >= MAX_ACTIVE_SERVICES) {
      return {
        deployed: false,
        reason: `Already at the cap of ${MAX_ACTIVE_SERVICES} active services. Use list_services to review them and remove one before deploying another — this bounds how much billed infrastructure you can create unattended.`,
      };
    }

    const sandbox = await ctx.getSandbox();
    const { files, truncated } = await collectSandboxFiles(sandbox, sourceDir);
    if (files.length === 0) {
      return { deployed: false, reason: `No readable files found under ${sourceDir}.` };
    }

    const wallet = await getOrCreateWallet();
    const appBaseUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL
      ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
      : process.env.APP_BASE_URL;
    const serviceId = crypto.randomUUID();

    let stripeHelperIncluded = false;
    if (appBaseUrl) {
      const serviceSecret = await getOrCreateServiceRevenueSecret();
      files.push({
        file: "_automaton_stripe.js",
        data: buildStripeHelper(
          `${appBaseUrl}/api/service-revenue/checkout`,
          `${appBaseUrl}/api/service-revenue/confirm`,
          serviceSecret,
          serviceId,
          name,
        ),
      });
      stripeHelperIncluded = true;
    }

    let mppHelperIncluded = false;
    if (wallet.chainType === "evm") {
      const mppSecret = await getOrCreateMppSecretKey();
      files.push({
        file: "_automaton_mpp.js",
        data: buildMppHelper(
          mppSecret,
          wallet.address,
          mppNetwork,
          appBaseUrl ? `${appBaseUrl}/api/mpp/report` : undefined,
          appBaseUrl ? mppSecret : undefined,
        ),
      });
      ensureMppDependency(files);
      mppHelperIncluded = true;
    }

    const created = await createVercelDeployment(config, name, files);
    const finalState = await pollDeploymentReady(config, created.id);
    const readyUrl = finalState.url || created.url;

    if (finalState.readyState === "READY") {
      await registerService({
        id: serviceId,
        name,
        url: readyUrl,
        deploymentId: created.id,
        sourceDir,
      });
    }

    return {
      deployed: finalState.readyState === "READY",
      readyState: finalState.readyState,
      url: readyUrl,
      deploymentId: created.id,
      serviceId: finalState.readyState === "READY" ? serviceId : undefined,
      filesDeployed: files.length,
      truncated,
      stripeHelperIncluded,
      mppHelperIncluded,
      note: finalState.readyState === "TIMEOUT"
        ? `Deployment is still building — call deploy_service again with resumeDeploymentId: "${created.id}" to check on it (it will not be registered as a service until ready).`
        : truncated
          ? "Some files were skipped (count/size caps) — keep services lean: source + package.json, no node_modules or build output."
          : undefined,
    };
  },
});
