import { defineTool } from "eve/tools";
import { always } from "eve/tools/approval";
import { z } from "zod";
import { loadVercelDeployConfig, collectSandboxFiles, createVercelDeployment, pollDeploymentReady } from "../lib/vercel-deploy";
import { getOrCreateWallet } from "../lib/wallet";
import { getOrCreateX402SettleSecret } from "../lib/x402-secret";

/** Node helper a deployed service can require() to accept x402 payments without ever touching the private key. */
function buildX402Helper(settleUrl: string, secret: string, payToAddress: string): string {
  return `// Auto-generated by deploy_service — do not hand-edit; the automaton owns this file.
// Usage from any Node HTTP handler:
//   const x402 = require('./_automaton_x402');
//   if (!req.headers['x-payment']) return res.status(402).json(x402.paymentRequired(0.01));
//   const result = await x402.settle(req.headers['x-payment'], 0.01, 'description');
//   if (!result.settled) return res.status(402).json(result);
//   // fulfill the paid request

const SETTLE_URL = ${JSON.stringify(settleUrl)};
const SETTLE_SECRET = ${JSON.stringify(secret)};
const PAY_TO_ADDRESS = ${JSON.stringify(payToAddress)};

function paymentRequired(amountUsdc, network) {
  network = network || 'eip155:8453';
  const maxAmountRequired = Math.round(amountUsdc * 1_000_000).toString();
  const usdcAddress = network === 'eip155:84532'
    ? '0x036CbD53842c5426634e7929541eC2318f3dCF7e'
    : '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
  return {
    x402Version: 1,
    accepts: [{
      scheme: 'exact',
      network,
      maxAmountRequired,
      payToAddress: PAY_TO_ADDRESS,
      usdcAddress,
      requiredDeadlineSeconds: 300,
    }],
  };
}

async function settle(paymentHeader, minAmountUsdc, description) {
  const resp = await fetch(SETTLE_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-automaton-settle-secret': SETTLE_SECRET },
    body: JSON.stringify({ payment: paymentHeader, minAmountUsdc, description }),
  });
  return resp.json();
}

module.exports = { paymentRequired, settle, PAY_TO_ADDRESS };
`;
}

export default defineTool({
  description:
    "Deploy a directory you've built in your sandbox (with bash/write_file) as its own real, public Vercel project — a genuine public URL others can reach and pay for, not a sandbox-only preview. This is how you actually host a paid service instead of just building one nobody can access. A ready-made `_automaton_x402.js` helper is injected automatically so a Node service can accept real x402 USDC payments without ever touching your private key (see the file's own usage comment). Requires AUTOMATON_VERCEL_TOKEN to be configured. Always requires creator approval since it creates new billed infrastructure under your Vercel account.",
  approval: always(),
  inputSchema: z.object({
    name: z.string().min(1).max(64).describe("Project name — becomes part of the deployment URL"),
    sourceDir: z.string().min(1).describe("Absolute sandbox path to the directory to deploy, e.g. /workspace/services/my-api"),
  }),
  async execute({ name, sourceDir }, ctx) {
    const config = loadVercelDeployConfig();
    if (!config) {
      return {
        deployed: false,
        reason: "AUTOMATON_VERCEL_TOKEN is not set. The creator needs to add a Vercel API token (with deploy scope) as an env var before you can deploy public services.",
      };
    }

    const sandbox = await ctx.getSandbox();
    const { files, truncated } = await collectSandboxFiles(sandbox, sourceDir);
    if (files.length === 0) {
      return { deployed: false, reason: `No readable files found under ${sourceDir}.` };
    }

    const wallet = await getOrCreateWallet();
    const settleBaseUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL
      ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
      : process.env.APP_BASE_URL;
    if (wallet.chainType === "evm" && settleBaseUrl) {
      const secret = await getOrCreateX402SettleSecret();
      files.push({
        file: "_automaton_x402.js",
        data: buildX402Helper(`${settleBaseUrl}/api/x402/settle`, secret, wallet.address),
      });
    }

    const created = await createVercelDeployment(config, name, files);
    const finalState = await pollDeploymentReady(config, created.id);

    return {
      deployed: finalState.readyState === "READY",
      readyState: finalState.readyState,
      url: finalState.url || created.url,
      filesDeployed: files.length,
      truncated,
      x402HelperIncluded: wallet.chainType === "evm" && !!settleBaseUrl,
      note: truncated
        ? "Some files were skipped (count/size caps) — keep services lean: source + package.json, no node_modules or build output."
        : undefined,
    };
  },
});
